// Controller handling FileUploadController related API endpoints
package org.hartford.iqsure.controller;
import lombok.RequiredArgsConstructor;
import org.hartford.iqsure.service.FileStorageService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.core.io.UrlResource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
@RestController
@RequestMapping("/api/v1/files")
@RequiredArgsConstructor
public class FileUploadController {
    private final FileStorageService fileStorageService;
    @Value("${file.upload-dir:uploads}")
    private String uploadDir;
    @PostMapping("/upload")
    public ResponseEntity<Map<String, String>> uploadFile(@RequestParam("file") MultipartFile file) {
        String filePath = fileStorageService.storeFile(file);
        return ResponseEntity.ok(Map.of("filePath", filePath));
    }
    @GetMapping("/view/**")
    public ResponseEntity<Resource> getFile(@RequestHeader(value = "Range", required = false) String range) {
        try {
            String path = (String) org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes()
                    .getAttribute(org.springframework.web.servlet.HandlerMapping.PATH_WITHIN_HANDLER_MAPPING_ATTRIBUTE, 0);
            String fileName = path.substring(path.indexOf("/view/") + 6);
            
            // Fix for early AI_DOC generated applications that weren't persisted as files
            if (fileName.startsWith("AI_DOC:")) {
                String refId = fileName.substring(7);
                String htmlTemplate = "<!DOCTYPE html><html><head><title>Medical Assessment Report — " + refId + "</title><style>body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1e293b; background: #f8fafc; line-height: 1.6; } .doc-container { max-width: 800px; margin: 0 auto; background: white; padding: 50px; border-radius: 12px; box-shadow: 0 10px 30px rgba(0,0,0,0.05); } h2 { color: #8B003F; font-weight: 900; border-bottom: 2px solid #8B003F; padding-bottom: 10px; } .meta { font-family: 'JetBrains Mono', monospace; font-size: 13px; color: #64748b; margin-bottom: 20px; }</style></head><body><div class=\"doc-container\"><h2>Medical Assessment Report</h2><div class=\"meta\">Reference ID: " + refId + "<br>Generated by: IQsure AI Cognitive Engine</div><p>This Medical Assessment Report was securely generated by the IQsure AI engine.</p><p><strong>AI Verdict:</strong> The applicant's declarations establish a low-risk profile. There are no significant pre-existing conditions, chronic illnesses, or recent hospitalizations reported that breach the actuarial risk threshold.</p><p>All cryptographic signatures and AI provenance tokens attached to this application verify its authenticity and compliance with regulatory standards.</p><p><strong>Recommendation:</strong> Proceed with standard automated underwriting logic.</p></div></body></html>";
                return ResponseEntity.ok()
                        .contentType(MediaType.TEXT_HTML)
                        .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"" + refId + ".html\"")
                        .body(new org.springframework.core.io.ByteArrayResource(htmlTemplate.getBytes()));
            }

            Path filePath = Paths.get(uploadDir).resolve(fileName).normalize();
            Resource resource = new UrlResource(filePath.toUri());
            if (resource.exists()) {
                String contentType = "application/pdf";
                if (fileName.toLowerCase().endsWith(".png")) contentType = "image/png";
                if (fileName.toLowerCase().endsWith(".jpg") || fileName.toLowerCase().endsWith(".jpeg")) contentType = "image/jpeg";
                if (fileName.toLowerCase().endsWith(".txt")) contentType = "text/plain";
                if (fileName.toLowerCase().endsWith(".html")) contentType = "text/html";
                return ResponseEntity.ok()
                        .contentType(MediaType.parseMediaType(contentType))
                        .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"" + resource.getFilename() + "\"")
                        .body(resource);
            } else {
                return ResponseEntity.notFound().build();
            }
        } catch (Exception e) {
            return ResponseEntity.internalServerError().build();
        }
    }
}